/**
 * Whitelist of allowed functions and methods for LLM test execution
 * This acts as a security measure to prevent arbitrary code execution
 */

// Allowed global constructors and functions
export const ALLOWED_GLOBALS = new Set([
  // JavaScript built-ins
  'Array',
  'ArrayBuffer',
  'Boolean',
  'Date',
  'Error',
  'JSON',
  'Map',
  'Math',
  'Number',
  'Object',
  'Promise',
  'RegExp',
  'Set',
  'String',
  'Symbol',
  'WeakMap',
  'WeakSet',
  'console',
  'undefined',
  'null',
  'true',
  'false',
  'NaN',
  'Infinity',
  'parseInt',
  'parseFloat',
  'isNaN',
  'isFinite',
  'decodeURI',
  'decodeURIComponent',
  'encodeURI',
  'encodeURIComponent',
  'escape',
  'unescape',
  // Console methods
  'log',
  'error',
  'warn',
  'info',
  'debug',
  'dir',
  'table',
  'trace',
  'assert',
  'count',
  'countReset',
  'group',
  'groupEnd',
  'time',
  'timeEnd',
  'timeLog',
]);

// Allowed Mepto/jQuery methods
export const ALLOWED_MEPTO_METHODS = new Set([
  // Core
  '$',
  'Mepto',
  'zepto',
  'fn',
  // DOM manipulation - class
  'addClass',
  'removeClass',
  'toggleClass',
  'hasClass',
  // DOM manipulation - attributes
  'attr',
  'removeAttr',
  'prop',
  'removeProp',
  'data',
  'removeData',
  'val',
  // DOM manipulation - content
  'html',
  'text',
  'empty',
  'clone',
  'remove',
  'detach',
  // DOM manipulation - insertion
  'append',
  'prepend',
  'after',
  'before',
  'appendTo',
  'prependTo',
  'insertAfter',
  'insertBefore',
  'replaceWith',
  'replaceAll',
  // Traversal
  'find',
  'closest',
  'parent',
  'parents',
  'parentsUntil',
  'children',
  'contents',
  'siblings',
  'next',
  'nextAll',
  'nextUntil',
  'prev',
  'prevAll',
  'prevUntil',
  'first',
  'last',
  'eq',
  'filter',
  'not',
  'is',
  'has',
  'add',
  'andSelf',
  'end',
  // CSS
  'css',
  'width',
  'height',
  'innerWidth',
  'innerHeight',
  'outerWidth',
  'outerHeight',
  'offset',
  'position',
  'scrollLeft',
  'scrollTop',
  // Events
  'on',
  'off',
  'one',
  'trigger',
  'triggerHandler',
  'bind',
  'unbind',
  'delegate',
  'undelegate',
  'click',
  'dblclick',
  'mousedown',
  'mouseup',
  'mousemove',
  'mouseover',
  'mouseout',
  'mouseenter',
  'mouseleave',
  'keydown',
  'keyup',
  'keypress',
  'submit',
  'change',
  'focus',
  'blur',
  'focusin',
  'focusout',
  'resize',
  'scroll',
  'select',
  'hover',
  'ready',
  // Forms
  'serialize',
  'serializeArray',
  // Effects
  'show',
  'hide',
  'toggle',
  'fadeIn',
  'fadeOut',
  'fadeTo',
  'fadeToggle',
  'slideDown',
  'slideUp',
  'slideToggle',
  'animate',
  'stop',
  'delay',
  'clearQueue',
  'queue',
  'dequeue',
  // Utilities
  'each',
  'map',
  'get',
  'index',
  'toArray',
  'push',
  'pop',
  'shift',
  'unshift',
  'slice',
  'splice',
  'concat',
  'length',
  'size',
  'pluck',
  // Static utilities
  'extend',
  'trim',
  'type',
  'isArray',
  'isFunction',
  'isWindow',
  'isPlainObject',
  'isObject',
  'isNumeric',
  'isEmptyObject',
  'camelCase',
  'dasherize',
  'parseJSON',
  'noop',
  'identity',
  'grep',
  'inArray',
  'merge',
  'unique',
  'makeArray',
  'contains',
  'ajax',
  'get',
  'post',
  'getJSON',
  'getScript',
  'param',
  'Deferred',
  'when',
  'Callbacks',
  'Event',
  'proxy',
  // Browser detection
  'browser',
  'os',
  'support',
]);

// Allowed DOM API methods (read-only for safety)
export const ALLOWED_DOM_METHODS = new Set([
  'getElementById',
  'getElementsByClassName',
  'getElementsByTagName',
  'getElementsByName',
  'querySelector',
  'querySelectorAll',
  'createElement',
  'createTextNode',
  'createDocumentFragment',
  'createComment',
  'cloneNode',
  'contains',
  'hasChildNodes',
  'isEqualNode',
  'isSameNode',
  'compareDocumentPosition',
  'lookupPrefix',
  'lookupNamespaceURI',
  'isDefaultNamespace',
  'normalize',
  'getAttribute',
  'getAttributeNS',
  'getAttributeNames',
  'hasAttribute',
  'hasAttributeNS',
  'matches',
  'closest',
  'getBoundingClientRect',
  'getClientRects',
  'scrollIntoView',
  'scrollIntoViewIfNeeded',
  'getElementsByTagNameNS',
  'getRootNode',
  // Node properties (read-only)
  'nodeType',
  'nodeName',
  'nodeValue',
  'textContent',
  'innerHTML',
  'outerHTML',
  'tagName',
  'id',
  'className',
  'classList',
  'attributes',
  'style',
  'children',
  'childNodes',
  'firstChild',
  'lastChild',
  'parentNode',
  'parentElement',
  'nextSibling',
  'previousSibling',
  'nextElementSibling',
  'previousElementSibling',
  'ownerDocument',
  // Element properties
  'clientWidth',
  'clientHeight',
  'clientTop',
  'clientLeft',
  'offsetWidth',
  'offsetHeight',
  'offsetTop',
  'offsetLeft',
  'scrollWidth',
  'scrollHeight',
  'scrollTop',
  'scrollLeft',
  // Document properties
  'documentElement',
  'body',
  'head',
  'title',
  'URL',
  'documentURI',
  'domain',
  'referrer',
  'cookie',
  'lastModified',
  'readyState',
  'characterSet',
  'charset',
  'inputEncoding',
  'defaultView',
  'implementation',
  'doctype',
  // Window properties
  'location',
  'navigator',
  'innerWidth',
  'innerHeight',
  'outerWidth',
  'outerHeight',
  'screenX',
  'screenY',
  'screenLeft',
  'screenTop',
  'devicePixelRatio',
  'visualViewport',
  'length',
  'top',
  'parent',
  'opener',
  'self',
  'window',
]);

// Check if a method name is allowed
export function isAllowedMethod(name: string): boolean {
  return (
    ALLOWED_GLOBALS.has(name) ||
    ALLOWED_MEPTO_METHODS.has(name) ||
    ALLOWED_DOM_METHODS.has(name)
  );
}

// Get all allowed methods for documentation
export function getAllAllowedMethods(): string[] {
  return [
    ...ALLOWED_GLOBALS,
    ...ALLOWED_MEPTO_METHODS,
    ...ALLOWED_DOM_METHODS,
  ];
}
